### ISSUE TITLE
Identify dtmf microphone in the L and R channels separately

### ISSUE THREAD

**Issue by evedostomazi** [bert2/DtmfDetection#3]
Is it possible to implement this procedure in the current dll ? If so, could you please send me a sample code?

**Comment by bert2** [comment]
Analyzing all channels separately is currently not possible. Your only option is splitting the input stream in your application and analyzing both streams.

However this is of course quite inefficient. So multi channel support definitely makes sense, but requires quite a few changes and I'm not sure when I'll find the time to implement it.

Could you provide me a audio file with different DTMF tones on separate channels for testing?

**Comment by evedostomazi** [comment]
Hello , yes when you have the attached file the link to your download.
thank you.

**Comment by bert2** [comment]
Ignore the above commit reference. That was a typo. Actually issue #2 has been fixed with the commit mentioned above. Issue #3 is still open and in progress now.

**Comment by bert2** [comment]
The issue has been fixed.  It is now possible to analyze each audio channel of multi-channel audio separately. However, by default this is deactivated and a (now proper) conversion to mono is done first. It can be activated by setting the `forceMono` flag of the [DtmfTones()](https://github.com/bert2/DtmfDetection/blob/master/DtmfDetection.NAudio/WaveStreamExtensions.cs) method or the [LiveAudioDtmfAnalyzer()](https://github.com/bert2/DtmfDetection/blob/master/DtmfDetection.NAudio/LiveAudioDtmfAnalyzer.cs) constructor to false.
See the updated examples in the [README](https://github.com/bert2/DtmfDetection/blob/master/README.md) or the [integration tests](https://github.com/bert2/DtmfDetection/blob/master/DtmfDetection.IntegrationTests/AudioFileTests.cs) for more.

**Comment by evedostomazi** [comment]
Thank you very much, here it is working correctly.
Now I want to learn how to control the volume, and if I can make mp3 recordings of the conversations.
