### ISSUE TITLE
Is it possible to use a named pipe (fifo) as input of NAudio?

### ISSUE THREAD

**Issue by moving-digital** [bert2/DtmfDetection#65]
Hi, @bert2 

I'm working on a requirement where I'm transcoding some live audio stream from M1-L2/AAC to PCM .wav, on the fly.

Then, I need to feed NAudio with that live .wav audio stream, because it doesn't come from any audio device (mic/speaker) but from the network.

I'm wondering if it is possible to use a named pipe (fifo) as input ?

I'm aware this may have its own challenge since ultimately this named pipe is a kinda file, so NAudio may not understand what's going on, therefore my question.

If the above is not possible, is there any other alternatives?

**Comment by bert2** [comment]
I think this question is better suited for the NAudio repository. DtmfDetection.NAudio can construct a `BackgroundAnalyzer` from any `IWaveIn`. So you best ask over there how you can turn a named pipe into an `IWaveIn`.

**Comment by bert2** [comment]
This might also be helpful: https://github.com/bert2/DtmfDetection#providing-a-custom-source-of-sample-data

**Comment by moving-digital** [comment]
> I think this question is better suited for the NAudio repository. DtmfDetection.NAudio can construct a `BackgroundAnalyzer` from any `IWaveIn`. So you best ask over there how you can turn a named pipe into an `IWaveIn`.

Yeah, I agree with you. But no reply from NAudio side, therefore I tried my luck with you. Thanks anyways!
