### ISSUE TITLE
Is it possible to change the detection frequency? 

### ISSUE THREAD

**Issue by moving-digital** [bert2/DtmfDetection#66]
Hi @bert2 

Is it possible to change the detection frequency, or process by T seconds intervals ?

By default, the DTMF duration is 40ms. But sometimes it can be 60, 70, or even 80ms.

So the precision of the result depends on the number of detection per seconds.

Is there a way to modify it with DtmfDetection, or is it fixed?

**Comment by bert2** [comment]
The library can handle DTMF tones of arbitrary length. An 80ms DTMF tone will be detected having a length of ~80 ms depending on the starting location. The detector resolution is ~25ms. So the length will always be multiples of that value.

See https://github.com/bert2/DtmfDetection#dtmf-tone-localization-accuracy
