### ISSUE TITLE
Identify off-hook phone

### ISSUE THREAD

**Issue by evedostomazi** [bert2/DtmfDetection#7]
Hello, I use the dll some time ago. I implemented a timer in my code to identify the conversation. When this timer reaches 15 seconds of silence, I close the recording of the conversation.
But often the voice of who is on the other side of the line is very low, which ends up in the middle of the conversation breaking the recording.
In short, is there a way to identify if the phone is off the hook, via audio, or some other dll?
Thank you.

**Comment by bert2** [comment]
Sorry, I can't help you with that.
