### ISSUE TITLE
System.Threading.ThreadAbortException

### ISSUE THREAD

**Issue by appstrage** [bert2/DtmfDetection#8]
Exception thrown: 'System.Threading.ThreadAbortException' in mscorlib.dll

I use VS2017, it's not working after successfully built. Showing error on when I pressing "o" or "m".

![image](https://user-images.githubusercontent.com/25323774/30258501-ed4e27d6-966e-11e7-8dc4-099eb92fb127.png)

**Comment by bert2** [comment]
Everytime you switch between capture modes or stop capturing with `[Esc]` an audio capture thread is being stopped. And the `ThreadAbortException` is just the way how stopping a thread is implemented in the .NET framework. Check the documentation of [`Thread.Abort()`](https://msdn.microsoft.com/en-us/library/ty8d3wta(v=vs.110).aspx):
> Raises a ThreadAbortException in the thread on which it is invoked, to begin the process of terminating the thread.

Could you be a little more specific what exactly is not working?
